#!/bin/sh

BACKUP_FOLDER=/backup/wordpress
NOW=$(date '+%Y-%m-%d')

TAR=$(which tar)

### Wordpress html folder to backup ###
DOCUMENTS=/var/www/html

[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER

FILE=${BACKUP_FOLDER}/${NOW}-${DOLIBARR_CONTAINER_NAME}-webfiles.gz
$TAR -czf $FILE $DOCUMENTS
